import type {
  AllometrySessionResult,
  IVIVESessionResult,
  DDISessionResult,
  ReportConfig,
  ExportFormat,
} from '@/types';

// ---------------------------------------------------------------------------
// JSON export
// ---------------------------------------------------------------------------

export function exportJSON(
  result: AllometrySessionResult | IVIVESessionResult | DDISessionResult,
  filename?: string
): void {
  const json = JSON.stringify(result, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  downloadBlob(blob, filename ?? `clinpharm-run-${result.metadata.runId}.json`);
}

// ---------------------------------------------------------------------------
// CSV export helpers
// ---------------------------------------------------------------------------

export function exportCSV(rows: Record<string, unknown>[], filename: string): void {
  if (rows.length === 0) return;
  const headers = Object.keys(rows[0]);
  const lines = [
    headers.join(','),
    ...rows.map(row =>
      headers.map(h => {
        const v = row[h];
        const s = v === null || v === undefined ? '' : String(v);
        return s.includes(',') || s.includes('"') || s.includes('\n')
          ? `"${s.replace(/"/g, '""')}"`
          : s;
      }).join(',')
    ),
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/csv' });
  downloadBlob(blob, filename);
}

// ---------------------------------------------------------------------------
// HTML report
// ---------------------------------------------------------------------------

export function exportHTMLReport(
  content: string,
  config: ReportConfig,
  filename?: string
): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${config.title} — ClinPharm Toolkit</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1e293b; max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
    h1 { color: #1e1b4b; font-size: 22px; border-bottom: 2px solid #4f46e5; padding-bottom: 8px; }
    h2 { color: #312e81; font-size: 16px; margin-top: 28px; }
    h3 { color: #3730a3; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
    th { background: #1e1b4b; color: white; padding: 6px 10px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
    td { padding: 5px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .equation { font-family: 'Courier New', monospace; background: #f1f5f9; padding: 6px 10px; border-left: 3px solid #4f46e5; margin: 6px 0; font-size: 12px; }
    .warning { padding: 8px 12px; border-left: 4px solid #f59e0b; background: #fffbeb; margin: 6px 0; font-size: 12px; }
    .error-warn { border-color: #ef4444; background: #fef2f2; }
    .disclaimer { font-size: 11px; color: #64748b; border: 1px solid #cbd5e1; padding: 10px; border-radius: 4px; margin-bottom: 20px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
    .badge-risk { background: #fee2e2; color: #991b1b; }
    .badge-no_risk { background: #dcfce7; color: #166534; }
    .badge-potential_risk { background: #fef9c3; color: #854d0e; }
    .section-divider { border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0; }
  </style>
</head>
<body>
  <div class="disclaimer">
    <strong>Disclaimer:</strong> ${config.disclaimer}
  </div>
  ${content}
  <hr class="section-divider"/>
  <p style="font-size:11px;color:#94a3b8;">
    Generated by ClinPharm Toolkit v1.0.0 on ${new Date().toUTCString()}
  </p>
</body>
</html>`;
  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, filename ?? `clinpharm-report-${Date.now()}.html`);
}

// ---------------------------------------------------------------------------
// PDF export via jsPDF
// ---------------------------------------------------------------------------

export async function exportPDFReport(
  htmlContent: string,
  config: ReportConfig,
  filename?: string
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  // Title page
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 27, 75);
  doc.text(config.title, margin, 30);

  doc.setFontSize(12);
  doc.setTextColor(71, 85, 105);
  doc.text(`Compound: ${config.compoundName}`, margin, 44);
  if (config.projectCode) doc.text(`Project: ${config.projectCode}`, margin, 52);
  doc.text(`Date: ${config.date}`, margin, 60);
  if (config.author) doc.text(`Author: ${config.author}`, margin, 68);

  doc.setDrawColor(79, 70, 229);
  doc.setLineWidth(0.5);
  doc.line(margin, 74, pageWidth - margin, 74);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const disclaimer = doc.splitTextToSize(config.disclaimer, contentWidth);
  doc.text(disclaimer, margin, 82);

  doc.addPage();

  // Plain text fallback for content
  const plainText = htmlContent
    .replace(/<[^>]*>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);

  const lines = doc.splitTextToSize(plainText, contentWidth);
  let y = margin;
  const lineH = 5;
  const pageH = doc.internal.pageSize.getHeight() - margin;

  for (const line of lines) {
    if (y + lineH > pageH) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  doc.save(filename ?? `clinpharm-report-${Date.now()}.pdf`);
}

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------

export function exportMarkdown(content: string, filename?: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  downloadBlob(blob, filename ?? `clinpharm-report-${Date.now()}.md`);
}

// ---------------------------------------------------------------------------
// Chart image export
// ---------------------------------------------------------------------------

export function exportPlotImage(svgElement: SVGElement, filename: string, format: 'svg' | 'png' = 'png'): void {
  if (format === 'svg') {
    const serializer = new XMLSerializer();
    const svgStr = serializer.serializeToString(svgElement);
    const blob = new Blob([svgStr], { type: 'image/svg+xml' });
    downloadBlob(blob, filename);
    return;
  }

  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const serializer = new XMLSerializer();
  const svgStr = serializer.serializeToString(svgElement);
  const img = new Image();
  const url = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgStr)));
  img.onload = () => {
    canvas.width = img.width || 800;
    canvas.height = img.height || 600;
    ctx.drawImage(img, 0, 0);
    canvas.toBlob(blob => {
      if (blob) downloadBlob(blob, filename);
    }, 'image/png');
  };
  img.src = url;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function formatNumber(v: number | undefined | null, decimals = 3): string {
  if (v === undefined || v === null || isNaN(v)) return '—';
  if (Math.abs(v) >= 10000 || (Math.abs(v) < 0.001 && v !== 0)) {
    return v.toExponential(2);
  }
  return v.toFixed(decimals);
}

export function formatFoldError(fe: number | undefined): string {
  if (fe === undefined || isNaN(fe)) return '—';
  const val = fe >= 1 ? fe : 1 / fe;
  const dir = fe >= 1 ? '↑' : '↓';
  return `${val.toFixed(2)}× ${dir}`;
}

// Generate allometry report HTML content
export function buildAllometryReportHTML(result: AllometrySessionResult): string {
  const { compound, inputs, finalResults, warnings, assumptions, metadata } = result;
  let html = `<h1>Allometric Scaling Report</h1>`;
  html += `<p><strong>Compound:</strong> ${compound.name}</p>`;
  html += `<p><strong>Run ID:</strong> ${metadata.runId}</p>`;
  html += `<p><strong>Date:</strong> ${metadata.timestamp}</p>`;

  html += `<h2>Input Data</h2>`;
  html += `<table><tr><th>Species</th><th>BW (kg)</th><th>CL (mL/min)</th><th>Vss (L)</th><th>fup</th></tr>`;
  for (const d of inputs.animalData.filter(x => x.include)) {
    html += `<tr><td>${d.label}</td><td>${d.bodyWeight_kg}</td><td>${formatNumber(d.CL_abs)}</td><td>${formatNumber(d.Vss_abs)}</td><td>${d.fup ?? '—'}</td></tr>`;
  }
  html += `</table>`;

  html += `<h2>Results by Method</h2>`;
  for (const r of finalResults.methodResults) {
    html += `<h3>${r.label}</h3>`;
    if (r.regressionCL) {
      html += `<div class="equation">CL = ${formatNumber(r.regressionCL.a, 4)} × BW<sup>${formatNumber(r.regressionCL.slope, 3)}</sup> &nbsp; R²=${formatNumber(r.regressionCL.rSquared, 4)}</div>`;
    }
    if (r.predictedCL_human !== undefined) {
      html += `<p>Predicted Human CL: <strong>${formatNumber(r.predictedCL_human)} mL/min</strong></p>`;
    }
    if (r.predictedVss_human !== undefined) {
      html += `<p>Predicted Human Vss: <strong>${formatNumber(r.predictedVss_human)} L</strong></p>`;
    }
    if (r.AAFE_CL !== undefined) {
      html += `<p>AAFE (CL): ${formatNumber(r.AAFE_CL, 3)}</p>`;
    }
  }

  if (warnings.length > 0) {
    html += `<h2>Warnings</h2>`;
    for (const w of warnings) {
      html += `<div class="warning">[${w.severity.toUpperCase()}] ${w.message}</div>`;
    }
  }

  if (assumptions.length > 0) {
    html += `<h2>Assumptions</h2><ul>`;
    for (const a of assumptions) html += `<li>${a}</li>`;
    html += `</ul>`;
  }

  return html;
}
