import React, { useState, useCallback } from 'react';
import {
  FileText, Upload, Download, Trash2, ChevronRight,
  BarChart2, FileJson, Globe, FileCode
} from 'lucide-react';
import type {
  AllometrySessionResult, IVIVESessionResult, DDISessionResult,
  UploadedSession, ReportConfig, ExportFormat, ModuleType,
} from '@/types';
import { useAppStore } from '@/store';
import { parseUploadedFile, runLabel, deserializeSession } from '@/utils/session';
import {
  exportJSON, exportHTMLReport, exportMarkdown, exportCSV,
  buildAllometryReportHTML, formatNumber,
} from '@/utils/export';

const DEFAULT_DISCLAIMER =
  'This report was generated by ClinPharm Toolkit. All predictions are exploratory and assumption-dependent. ' +
  'Results are intended for research and internal decision-making purposes only. ' +
  'Clinical decisions must not be based solely on these computational predictions. ' +
  'Regulatory submissions require additional validation.';

function defaultConfig(compound: string): ReportConfig {
  return {
    title: `Clinical Pharmacology Prediction Report`,
    compoundName: compound || 'Unknown Compound',
    author: '',
    organization: '',
    date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    includeEquations: true,
    includeIntermediates: true,
    includeWarnings: true,
    includeAssumptions: true,
    includePlots: true,
    includeAppendix: true,
    modulesToInclude: ['allometry', 'ivive', 'ddi'],
    exportFormats: ['html', 'json'],
    disclaimer: DEFAULT_DISCLAIMER,
  };
}

// ---- Session Upload Panel ----
function UploadPanel({
  sessions,
  onUpload,
  onRemove,
}: {
  sessions: UploadedSession[];
  onUpload: (s: UploadedSession) => void;
  onRemove: (i: number) => void;
}) {
  const [dragging, setDragging] = useState(false);

  async function handleFiles(files: FileList | null) {
    if (!files) return;
    for (const file of Array.from(files)) {
      try {
        const session = await parseUploadedFile(file);
        onUpload(session);
      } catch (err) {
        alert(`Could not parse ${file.name}: ${(err as Error).message}`);
      }
    }
  }

  const MODULE_COLORS: Record<ModuleType, string> = {
    allometry: 'bg-indigo-100 text-indigo-800',
    ivive: 'bg-teal-100 text-teal-800',
    ddi: 'bg-amber-100 text-amber-800',
    reporting: 'bg-purple-100 text-purple-800',
  };

  return (
    <div className="space-y-3">
      <div
        onDragOver={e => { e.preventDefault(); setDragging(true); }}
        onDragLeave={() => setDragging(false)}
        onDrop={e => { e.preventDefault(); setDragging(false); handleFiles(e.dataTransfer.files); }}
        className={`border-2 border-dashed rounded-lg p-6 text-center transition-colors cursor-pointer ${
          dragging ? 'border-purple-400 bg-purple-50' : 'border-slate-300 hover:border-purple-400 hover:bg-purple-50/30'
        }`}
        onClick={() => document.getElementById('session-upload')?.click()}
      >
        <Upload size={32} className="mx-auto text-slate-400 mb-2" />
        <p className="text-sm font-medium text-slate-700">Drop session JSON files here</p>
        <p className="text-xs text-slate-400 mt-1">Or click to browse — supports .json exports from any ClinPharm module</p>
        <input
          id="session-upload"
          type="file"
          accept=".json"
          multiple
          className="hidden"
          onChange={e => handleFiles(e.target.files)}
        />
      </div>

      {sessions.length > 0 && (
        <div className="space-y-2">
          {sessions.map((s, i) => (
            <div key={i} className="flex items-center justify-between bg-white border border-slate-200 rounded-lg px-3 py-2.5">
              <div className="flex items-center gap-2 min-w-0">
                <span className={`shrink-0 text-[10px] font-bold uppercase px-2 py-0.5 rounded ${MODULE_COLORS[s.moduleType]}`}>
                  {s.moduleType}
                </span>
                <div className="min-w-0">
                  <p className="text-xs font-medium text-slate-700 truncate">{s.filename}</p>
                  <p className="text-[10px] text-slate-400">
                    {runLabel(s.result.metadata)} · {s.result.compound?.name ?? '—'}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <button
                  onClick={() => exportJSON(s.result, `${s.moduleType}-${s.result.metadata.runId}.json`)}
                  title="Re-download JSON"
                  className="p-1 text-slate-400 hover:text-indigo-600"
                >
                  <Download size={13} />
                </button>
                <button onClick={() => onRemove(i)} className="p-1 text-slate-400 hover:text-red-600">
                  <Trash2 size={13} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ---- Report Config Panel ----
function ReportConfigPanel({
  config,
  onChange,
}: {
  config: ReportConfig;
  onChange: (c: ReportConfig) => void;
}) {
  function set<K extends keyof ReportConfig>(key: K, value: ReportConfig[K]) {
    onChange({ ...config, [key]: value });
  }

  function toggleFormat(fmt: ExportFormat) {
    const formats = config.exportFormats.includes(fmt)
      ? config.exportFormats.filter(f => f !== fmt)
      : [...config.exportFormats, fmt];
    set('exportFormats', formats);
  }

  function toggleModule(mod: ModuleType) {
    const mods = config.modulesToInclude.includes(mod)
      ? config.modulesToInclude.filter(m => m !== mod)
      : [...config.modulesToInclude, mod];
    set('modulesToInclude', mods as ModuleType[]);
  }

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div>
          <label className="block text-xs text-slate-500 mb-0.5">Report title</label>
          <input
            type="text"
            value={config.title}
            onChange={e => set('title', e.target.value)}
            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm focus:outline-none focus:border-purple-400"
          />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-0.5">Compound name</label>
          <input
            type="text"
            value={config.compoundName}
            onChange={e => set('compoundName', e.target.value)}
            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm focus:outline-none focus:border-purple-400"
          />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-0.5">Author</label>
          <input
            type="text"
            value={config.author ?? ''}
            onChange={e => set('author', e.target.value)}
            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm focus:outline-none focus:border-purple-400"
          />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-0.5">Organization</label>
          <input
            type="text"
            value={config.organization ?? ''}
            onChange={e => set('organization', e.target.value)}
            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm focus:outline-none focus:border-purple-400"
          />
        </div>
      </div>

      <div>
        <label className="block text-xs text-slate-500 mb-0.5">Project code</label>
        <input
          type="text"
          value={config.projectCode ?? ''}
          onChange={e => set('projectCode', e.target.value)}
          placeholder="e.g. CPH-2024-001"
          className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm focus:outline-none focus:border-purple-400"
        />
      </div>

      <div>
        <p className="text-xs font-semibold text-slate-600 mb-1">Include in report</p>
        <div className="grid grid-cols-2 gap-1">
          {[
            { key: 'includeEquations', label: 'Equations used' },
            { key: 'includeIntermediates', label: 'Intermediate results' },
            { key: 'includeWarnings', label: 'Warnings' },
            { key: 'includeAssumptions', label: 'Assumptions' },
            { key: 'includePlots', label: 'Plots' },
            { key: 'includeAppendix', label: 'Formula appendix' },
          ].map(({ key, label }) => (
            <label key={key} className="flex items-center gap-2 text-sm text-slate-700 cursor-pointer">
              <input
                type="checkbox"
                checked={config[key as keyof ReportConfig] as boolean}
                onChange={e => set(key as keyof ReportConfig, e.target.checked as ReportConfig[keyof ReportConfig])}
                className="accent-purple-600"
              />
              {label}
            </label>
          ))}
        </div>
      </div>

      <div>
        <p className="text-xs font-semibold text-slate-600 mb-1">Modules to include</p>
        <div className="flex gap-2">
          {(['allometry', 'ivive', 'ddi'] as ModuleType[]).map(mod => (
            <label key={mod} className="flex items-center gap-1.5 text-sm cursor-pointer">
              <input
                type="checkbox"
                checked={config.modulesToInclude.includes(mod)}
                onChange={() => toggleModule(mod)}
                className="accent-purple-600"
              />
              {mod.toUpperCase()}
            </label>
          ))}
        </div>
      </div>

      <div>
        <p className="text-xs font-semibold text-slate-600 mb-1">Export formats</p>
        <div className="flex flex-wrap gap-2">
          {[
            { fmt: 'html' as ExportFormat, icon: Globe, label: 'HTML' },
            { fmt: 'pdf' as ExportFormat, icon: FileText, label: 'PDF' },
            { fmt: 'json' as ExportFormat, icon: FileJson, label: 'JSON' },
            { fmt: 'markdown' as ExportFormat, icon: FileCode, label: 'Markdown' },
          ].map(({ fmt, icon: Icon, label }) => (
            <label key={fmt} className={`flex items-center gap-1.5 px-3 py-1.5 rounded border cursor-pointer text-xs font-medium transition-colors ${
              config.exportFormats.includes(fmt)
                ? 'bg-purple-600 text-white border-purple-600'
                : 'bg-white text-slate-600 border-slate-300 hover:border-purple-400'
            }`}>
              <input
                type="checkbox"
                checked={config.exportFormats.includes(fmt)}
                onChange={() => toggleFormat(fmt)}
                className="hidden"
              />
              <Icon size={13} /> {label}
            </label>
          ))}
        </div>
      </div>

      <div>
        <label className="block text-xs text-slate-500 mb-0.5">Disclaimer text</label>
        <textarea
          value={config.disclaimer}
          onChange={e => set('disclaimer', e.target.value)}
          rows={3}
          className="w-full border border-slate-300 rounded px-2 py-1.5 text-xs text-slate-600 focus:outline-none focus:border-purple-400 resize-none"
        />
      </div>
    </div>
  );
}

// ---- Saved Runs Panel ----
function SavedRunsPanel({
  runs,
  onExport,
}: {
  runs: Array<AllometrySessionResult | IVIVESessionResult | DDISessionResult>;
  onExport: (run: AllometrySessionResult | IVIVESessionResult | DDISessionResult) => void;
}) {
  if (runs.length === 0) {
    return (
      <p className="text-sm text-slate-400 text-center py-8">
        No saved runs yet. Use "Save run" in any module.
      </p>
    );
  }

  const MODULE_BADGE: Record<ModuleType, string> = {
    allometry: 'bg-indigo-100 text-indigo-800',
    ivive: 'bg-teal-100 text-teal-800',
    ddi: 'bg-amber-100 text-amber-800',
    reporting: 'bg-purple-100 text-purple-800',
  };

  return (
    <div className="space-y-2">
      {runs.map((run, i) => (
        <div key={run.metadata.runId} className="flex items-center justify-between bg-white border border-slate-200 rounded-lg px-3 py-2.5">
          <div className="flex items-center gap-2 min-w-0">
            <span className={`shrink-0 text-[10px] font-bold uppercase px-2 py-0.5 rounded ${MODULE_BADGE[run.metadata.appType]}`}>
              {run.metadata.appType}
            </span>
            <div className="min-w-0">
              <p className="text-xs font-medium text-slate-700 truncate">
                {run.compound?.name ?? 'Unnamed'} — {runLabel(run.metadata)}
              </p>
              <p className="text-[10px] text-slate-400">
                Formula v{run.metadata.formulaSetVersion} · Physiology v{run.metadata.physiologyVersion}
              </p>
            </div>
          </div>
          <div className="flex gap-1 shrink-0">
            <button
              onClick={() => exportJSON(run)}
              className="p-1.5 text-slate-400 hover:text-indigo-600 transition-colors"
              title="Export JSON"
            >
              <FileJson size={14} />
            </button>
            <button
              onClick={() => onExport(run)}
              className="p-1.5 text-slate-400 hover:text-purple-600 transition-colors"
              title="Generate report"
            >
              <FileText size={14} />
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

// ---- Report Preview ----
function ReportPreview({ html }: { html: string }) {
  return (
    <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
      <div className="bg-slate-700 text-white text-xs px-3 py-1.5 flex items-center gap-1">
        <Globe size={12} /> Report Preview
      </div>
      <div
        className="p-6 prose prose-sm max-w-none max-h-[600px] overflow-y-auto text-sm"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}

// ---- Build HTML report from multiple sessions ----
function buildCombinedReportHTML(
  sessions: Array<AllometrySessionResult | IVIVESessionResult | DDISessionResult>,
  savedRuns: Array<AllometrySessionResult | IVIVESessionResult | DDISessionResult>,
  config: ReportConfig,
): string {
  const allSessions = [...sessions, ...savedRuns];
  if (allSessions.length === 0) {
    return `<p>No data loaded. Upload session files or save runs from the calculation modules first.</p>`;
  }

  let html = `<h1>${config.title}</h1>`;
  html += `<p><strong>Compound:</strong> ${config.compoundName}</p>`;
  html += `<p><strong>Date:</strong> ${config.date}</p>`;
  if (config.author) html += `<p><strong>Author:</strong> ${config.author}</p>`;
  if (config.organization) html += `<p><strong>Organization:</strong> ${config.organization}</p>`;
  html += `<hr/>`;

  for (const run of allSessions) {
    const type = run.metadata.appType;
    if (!config.modulesToInclude.includes(type)) continue;

    if (type === 'allometry') {
      html += buildAllometryReportHTML(run as AllometrySessionResult);
    } else if (type === 'ivive') {
      html += buildIVIVEHTML(run as IVIVESessionResult);
    } else if (type === 'ddi') {
      html += buildDDIHTML(run as DDISessionResult);
    }
    html += `<hr/>`;
  }

  if (config.includeAssumptions) {
    html += `<h2>Common Assumptions</h2><ul>`;
    html += `<li>All predictions are based on physiological parameter database v${allSessions[0]?.metadata.physiologyVersion}.</li>`;
    html += `<li>IVIVE uses hepatic clearance scaling only; non-hepatic routes not modeled.</li>`;
    html += `<li>DDI assessment follows static (R-value) framework; PBPK not performed.</li>`;
    html += `<li>Allometric relationships assume P = a × BW^b holds across selected species.</li>`;
    html += `</ul>`;
  }

  return html;
}

function buildIVIVEHTML(run: IVIVESessionResult): string {
  let html = `<h2>IVIVE — ${run.compound?.name ?? ''}</h2>`;
  html += `<p>Run ID: ${run.metadata.runId} | Date: ${run.metadata.timestamp}</p>`;
  const res = run.finalResults;
  if (res?.speciesResults) {
    html += `<table><tr><th>Species</th><th>CLint,invivo (mL/min)</th><th>Model</th><th>CLh pred (mL/min)</th><th>Eh</th><th>Category</th></tr>`;
    for (const sr of res.speciesResults) {
      for (const m of sr.modelOutputs) {
        html += `<tr><td>${sr.label}</td><td>${formatNumber(sr.CLint_invivo)}</td><td>${m.label}</td><td>${formatNumber(m.CLh_predicted)}</td><td>${m.Eh.toFixed(3)}</td><td>${m.ExtractionCategory}</td></tr>`;
      }
    }
    html += `</table>`;
  }
  return html;
}

function buildDDIHTML(run: DDISessionResult): string {
  let html = `<h2>DDI Assessment — ${run.compound?.name ?? ''}</h2>`;
  html += `<p>Run ID: ${run.metadata.runId} | Date: ${run.metadata.timestamp}</p>`;
  const res = run.finalResults;
  if (!res) return html;

  html += `<p>Overall Risk: <strong>${res.overallRisk?.toUpperCase().replace('_', ' ')}</strong></p>`;

  if (res.riskMatrix?.length > 0) {
    html += `<h3>Risk Matrix</h3><table><tr><th>Pathway</th><th>Type</th><th>Risk</th><th>Metric</th><th>Threshold</th></tr>`;
    for (const entry of res.riskMatrix) {
      html += `<tr><td>${entry.pathway}</td><td>${entry.type}</td><td class="badge-${entry.risk}">${entry.risk.replace('_', ' ')}</td><td>${entry.metric !== undefined ? entry.metric.toFixed(3) : '—'}</td><td>${entry.threshold !== undefined ? entry.threshold.toFixed(3) : '—'}</td></tr>`;
    }
    html += `</table>`;
  }
  return html;
}

// ---- Main module ----
export default function ReportingModule() {
  const { uploadedSessions, addUploadedSession, removeUploadedSession, savedRuns } = useAppStore();
  const [config, setConfig] = useState<ReportConfig>(defaultConfig(''));
  const [previewHTML, setPreviewHTML] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const generateReport = useCallback(async () => {
    setGenerating(true);
    try {
      const html = buildCombinedReportHTML(
        uploadedSessions.map(s => s.result),
        savedRuns,
        config,
      );
      setPreviewHTML(html);

      if (config.exportFormats.includes('html')) {
        exportHTMLReport(html, config, `${config.compoundName.replace(/\s+/g, '-')}-clinpharm-report.html`);
      }
      if (config.exportFormats.includes('json')) {
        const bundle = {
          config,
          uploadedSessions: uploadedSessions.map(s => s.result),
          savedRuns,
          generatedAt: new Date().toISOString(),
        };
        const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${config.compoundName.replace(/\s+/g, '-')}-report-bundle.json`;
        a.click();
        URL.revokeObjectURL(url);
      }
      if (config.exportFormats.includes('markdown')) {
        const md = htmlToMarkdown(html);
        exportMarkdown(md, `${config.compoundName.replace(/\s+/g, '-')}-report.md`);
      }
      if (config.exportFormats.includes('pdf')) {
        const { exportPDFReport } = await import('@/utils/export');
        await exportPDFReport(html, config, `${config.compoundName.replace(/\s+/g, '-')}-report.pdf`);
      }
    } finally {
      setGenerating(false);
    }
  }, [uploadedSessions, savedRuns, config]);

  const handleExportRun = useCallback((run: AllometrySessionResult | IVIVESessionResult | DDISessionResult) => {
    exportJSON(run);
  }, []);

  const totalSessions = uploadedSessions.length + savedRuns.length;

  return (
    <div className="min-h-full bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 px-6 py-4">
        <div className="flex items-center justify-between max-w-screen-2xl mx-auto">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-purple-600 flex items-center justify-center">
              <FileText size={18} className="text-white" />
            </div>
            <div>
              <h1 className="text-lg font-bold text-slate-900">Reporting & Results</h1>
              <p className="text-xs text-slate-500">Upload prior results, generate reports, export data</p>
            </div>
          </div>
          <button
            onClick={generateReport}
            disabled={generating || totalSessions === 0}
            className="flex items-center gap-2 px-5 py-1.5 bg-purple-600 text-white text-sm font-semibold rounded-md hover:bg-purple-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
          >
            <FileText size={14} />
            {generating ? 'Generating…' : `Generate Report${totalSessions > 0 ? ` (${totalSessions})` : ''}`}
          </button>
        </div>
      </div>

      <div className="max-w-screen-2xl mx-auto p-4 grid grid-cols-12 gap-4">

        {/* LEFT — Upload + Saved runs */}
        <div className="col-span-12 xl:col-span-4 space-y-4">
          <div className="bg-white rounded-lg border border-slate-200 p-4">
            <h3 className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-3">
              Upload Prior Session Files
            </h3>
            <UploadPanel
              sessions={uploadedSessions}
              onUpload={addUploadedSession}
              onRemove={removeUploadedSession}
            />
          </div>

          <div className="bg-white rounded-lg border border-slate-200 p-4">
            <h3 className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-3 flex items-center gap-2">
              Saved Runs from This Session
              {savedRuns.length > 0 && (
                <span className="bg-slate-200 text-slate-600 text-[10px] font-bold px-1.5 py-0.5 rounded-full">
                  {savedRuns.length}
                </span>
              )}
            </h3>
            <SavedRunsPanel runs={savedRuns} onExport={handleExportRun} />
          </div>
        </div>

        {/* MIDDLE — Config */}
        <div className="col-span-12 xl:col-span-4">
          <div className="bg-white rounded-lg border border-slate-200 p-4">
            <h3 className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-3">
              Report Configuration
            </h3>
            <ReportConfigPanel config={config} onChange={setConfig} />
          </div>
        </div>

        {/* RIGHT — Preview */}
        <div className="col-span-12 xl:col-span-4 space-y-4">
          {totalSessions === 0 ? (
            <div className="bg-white rounded-lg border border-dashed border-slate-300 p-8 text-center text-slate-400">
              <BarChart2 size={40} className="mx-auto mb-3 text-slate-300" />
              <p className="text-sm font-medium">No data loaded yet</p>
              <p className="text-xs mt-1 max-w-xs mx-auto">
                Upload session JSON files from prior runs, or save runs from the Allometry, IVIVE, or DDI modules.
              </p>
            </div>
          ) : (
            <div className="bg-purple-50 border border-purple-200 rounded-lg p-3 text-sm">
              <p className="font-semibold text-purple-800">
                {totalSessions} session{totalSessions > 1 ? 's' : ''} ready to report
              </p>
              <ul className="text-xs text-purple-600 mt-1 space-y-0.5">
                {uploadedSessions.map((s, i) => (
                  <li key={i} className="flex items-center gap-1">
                    <ChevronRight size={10} />
                    {s.moduleType.toUpperCase()} — {s.filename}
                  </li>
                ))}
                {savedRuns.map((r, i) => (
                  <li key={`saved-${i}`} className="flex items-center gap-1">
                    <ChevronRight size={10} />
                    {r.metadata.appType.toUpperCase()} — {r.compound?.name ?? 'Unnamed'} (session run)
                  </li>
                ))}
              </ul>
            </div>
          )}

          {previewHTML && (
            <ReportPreview html={previewHTML} />
          )}

          {/* Quick export section */}
          <div className="bg-white rounded-lg border border-slate-200 p-4">
            <h3 className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-2">Quick Export</h3>
            <div className="space-y-2">
              <button
                onClick={() => {
                  for (const s of uploadedSessions) exportJSON(s.result);
                  for (const r of savedRuns) exportJSON(r);
                }}
                disabled={totalSessions === 0}
                className="w-full flex items-center gap-2 px-3 py-2 text-sm border border-slate-300 rounded hover:bg-slate-50 disabled:opacity-50 transition-colors"
              >
                <FileJson size={14} className="text-slate-500" />
                Export all runs as JSON
              </button>
              <button
                onClick={() => {
                  const allRuns = [
                    ...uploadedSessions.map(s => s.result),
                    ...savedRuns,
                  ];
                  exportCSV(
                    allRuns.map(r => ({
                      run_id: r.metadata.runId,
                      module: r.metadata.appType,
                      compound: r.compound?.name ?? '—',
                      timestamp: r.metadata.timestamp,
                      formula_version: r.metadata.formulaSetVersion,
                    })),
                    'clinpharm-runs-summary.csv'
                  );
                }}
                disabled={totalSessions === 0}
                className="w-full flex items-center gap-2 px-3 py-2 text-sm border border-slate-300 rounded hover:bg-slate-50 disabled:opacity-50 transition-colors"
              >
                <Download size={14} className="text-slate-500" />
                Export run summary CSV
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function htmlToMarkdown(html: string): string {
  return html
    .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '# $1\n\n')
    .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '## $1\n\n')
    .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '### $1\n\n')
    .replace(/<strong>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<b>(.*?)<\/b>/gi, '**$1**')
    .replace(/<em>(.*?)<\/em>/gi, '*$1*')
    .replace(/<p[^>]*>(.*?)<\/p>/gi, '$1\n\n')
    .replace(/<li>(.*?)<\/li>/gi, '- $1\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}
